### ISSUE TITLE
How to install bwrap and bubblewrap? (Debian 8/Jessie)

### ISSUE THREAD

**Issue by RogerTarani** [Chris00/ocaml-bwrap#2]
How to install bwrap as well as bubblewrap which is a depext?

I'm currently messing with a simple 1.2.0 to 2.0.2 opam upgrade. I've even removed opam 1.2.0 so it's now an install problem. 
I used to install opam 2.0 on Debian 9 and bwrap quite easily. 
`opam init` warns that bwrap was not found and suggests to install bubblewrap.
But bubblewrap is not available from package manager (Debian Jessie).
And I don't succeed in installing bubblewrap from sources with the usual ./configure make make install.

What am I missing?
Thanks

**Comment by Chris00** [comment]
Solution given on [the forum](https://discuss.ocaml.org/t/how-to-install-bwrap-bubblewrap-linux/3086).

Note that this package is not used by `opam` — it uses its own sandboxing scripts.
